version: "3"

services:
  backend:
    image: frappe/erpnext:v15.81.1
    networks:
      - frappe_network
    deploy:
      restart_policy:
        condition: on-failure
    volumes:
      - sites:/home/frappe/frappe-bench/sites
      - logs:/home/frappe/frappe-bench/logs
      # Monter votre code source ERPNext personnalisé
      - ../erpnext-develop:/home/frappe/frappe-bench/apps/erpnext
    environment:
      DB_HOST: db
      DB_PORT: "3306"
      MYSQL_ROOT_PASSWORD: admin
      MARIADB_ROOT_PASSWORD: admin

  configurator:
    image: frappe/erpnext:v15.81.1
    networks:
      - frappe_network
    deploy:
      restart_policy:
        condition: none
    entrypoint:
      - bash
      - -c
    command:
      - >
        ls -1 apps > sites/apps.txt;
        bench set-config -g db_host $$DB_HOST;
        bench set-config -gp db_port $$DB_PORT;
        bench set-config -g redis_cache "redis://$$REDIS_CACHE";
        bench set-config -g redis_queue "redis://$$REDIS_QUEUE";
        bench set-config -g redis_socketio "redis://$$REDIS_QUEUE";
        bench set-config -gp socketio_port $$SOCKETIO_PORT;
    environment:
      DB_HOST: db
      DB_PORT: "3306"
      REDIS_CACHE: redis-cache:6379
      REDIS_QUEUE: redis-queue:6379
      SOCKETIO_PORT: "9000"
    volumes:
      - sites:/home/frappe/frappe-bench/sites
      - logs:/home/frappe/frappe-bench/logs
      - ../erpnext-develop:/home/frappe/frappe-bench/apps/erpnext

  create-site:
    image: frappe/erpnext:v15.81.1
    networks:
      - frappe_network
    deploy:
      restart_policy:
        condition: none
    entrypoint:
      - bash
      - -c
    command:
      - >
        wait-for-it -t 120 $$DB_HOST:$$DB_PORT;
        wait-for-it -t 120 $$REDIS_QUEUE:6379;
        wait-for-it -t 120 $$REDIS_CACHE:6379;
        bench new-site --admin-password admin --mariadb-root-password admin --install-app erpnext --set-default $$SITE_NAME;
    environment:
      DB_HOST: db
      DB_PORT: "3306"
      MARIADB_ROOT_PASSWORD: admin
      REDIS_CACHE: redis-cache:6379
      REDIS_QUEUE: redis-queue:6379
      SITE_NAME: dev-erpnext.localhost
    volumes:
      - sites:/home/frappe/frappe-bench/sites
      - logs:/home/frappe/frappe-bench/logs
      - ../erpnext-develop:/home/frappe/frappe-bench/apps/erpnext

  frontend:
    image: frappe/erpnext:v15.81.1
    networks:
      - frappe_network
    deploy:
      restart_policy:
        condition: on-failure
    ports:
      - "8080:8080"
    volumes:
      - sites:/home/frappe/frappe-bench/sites
      - logs:/home/frappe/frappe-bench/logs
      - ../erpnext-develop:/home/frappe/frappe-bench/apps/erpnext
    environment:
      DB_HOST: db
      DB_PORT: "3306"
      REDIS_CACHE: redis-cache:6379
      REDIS_QUEUE: redis-queue:6379
      SOCKETIO_PORT: "9000"

  websocket:
    image: frappe/erpnext:v15.81.1
    networks:
      - frappe_network
    deploy:
      restart_policy:
        condition: on-failure
    ports:
      - "9000:9000"
    volumes:
      - sites:/home/frappe/frappe-bench/sites
      - logs:/home/frappe/frappe-bench/logs
      - ../erpnext-develop:/home/frappe/frappe-bench/apps/erpnext
    environment:
      DB_HOST: db
      DB_PORT: "3306"
      REDIS_CACHE: redis-cache:6379
      REDIS_QUEUE: redis-queue:6379
      SOCKETIO_PORT: "9000"

  worker-short:
    image: frappe/erpnext:v15.81.1
    networks:
      - frappe_network
    deploy:
      restart_policy:
        condition: on-failure
    volumes:
      - sites:/home/frappe/frappe-bench/sites
      - logs:/home/frappe/frappe-bench/logs
      - ../erpnext-develop:/home/frappe/frappe-bench/apps/erpnext
    environment:
      DB_HOST: db
      DB_PORT: "3306"
      REDIS_CACHE: redis-cache:6379
      REDIS_QUEUE: redis-queue:6379
      SOCKETIO_PORT: "9000"
    command:
      - bench
      - worker
      - --queue
      - short

  worker-long:
    image: frappe/erpnext:v15.81.1
    networks:
      - frappe_network
    deploy:
      restart_policy:
        condition: on-failure
    volumes:
      - sites:/home/frappe/frappe-bench/sites
      - logs:/home/frappe/frappe-bench/logs
      - ../erpnext-develop:/home/frappe/frappe-bench/apps/erpnext
    environment:
      DB_HOST: db
      DB_PORT: "3306"
      REDIS_CACHE: redis-cache:6379
      REDIS_QUEUE: redis-queue:6379
      SOCKETIO_PORT: "9000"
    command:
      - bench
      - worker
      - --queue
      - long

  scheduler:
    image: frappe/erpnext:v15.81.1
    networks:
      - frappe_network
    deploy:
      restart_policy:
        condition: on-failure
    volumes:
      - sites:/home/frappe/frappe-bench/sites
      - logs:/home/frappe/frappe-bench/logs
      - ../erpnext-develop:/home/frappe/frappe-bench/apps/erpnext
    environment:
      DB_HOST: db
      DB_PORT: "3306"
      REDIS_CACHE: redis-cache:6379
      REDIS_QUEUE: redis-queue:6379
      SOCKETIO_PORT: "9000"
    command:
      - bench
      - schedule

  db:
    image: mariadb:10.6
    networks:
      - frappe_network
    deploy:
      restart_policy:
        condition: on-failure
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MARIADB_ROOT_PASSWORD: admin
    volumes:
      - db-data:/var/lib/mysql

  redis-cache:
    image: redis:6.2-alpine
    networks:
      - frappe_network
    deploy:
      restart_policy:
        condition: on-failure
    volumes:
      - redis-cache-data:/data

  redis-queue:
    image: redis:6.2-alpine
    networks:
      - frappe_network
    deploy:
      restart_policy:
        condition: on-failure
    volumes:
      - redis-queue-data:/data

networks:
  frappe_network:
    driver: bridge

volumes:
  sites:
  logs:
  db-data:
  redis-cache-data:
  redis-queue-data:
