version: '3.8'

services:
  db:
    image: mariadb:10.6
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: erpnext
      MYSQL_USER: erpnext
      MYSQL_PASSWORD: admin
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"

  redis:
    image: redis:6-alpine
    ports:
      - "6379:6379"

  erpnext:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DB_HOST=db
      - DB_USER=erpnext
      - DB_PASSWORD=admin
      - DB_NAME=erpnext
      - REDIS_HOST=redis
    depends_on:
      - db
      - redis
    volumes:
      - erpnext_data:/home/frappe/frappe-bench

volumes:
  db_data:
  erpnext_data: